services:
  rabbitmq:
    image: "rabbitmq:management"
    container_name: "rabbit"
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: "redis:5-alpine"
    container_name: "redis"
    ports:
      - "6379:6379"
  cassandra:
    image: "cassandra:3"
    container_name: "cassandra"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
  mysql:
    image: "mysql:8"
    container_name: "mysql"
    environment:
      MYSQL_DATABASE: "chatDB"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql-data:
  cassandra_data:
